name: dedala_dart
description: A declarative data layer written in Dart.
# author: bissl

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  extra_pedantic: ^4.0.0
  test: ^1.24.3
